export enum eVariantModal {
  newUser = "newUser",
  editUser = "editUser",
  newDev = "newDev",
  editDev = "editDev",
  moveDev = "moveDev",
  newOrg = "newOrg",
  editOrg = "editOrg",
  newJob = "newJobsTitle",
  editJob = "editJobsTitle",
  newWell = "newWell",
  editWell = "editWell",
  newLocation = "newLocation",
  editLocation = "editLocation",
  moveLocation = "moveLocation",
  newDevs = "newDevs",
  newScheme = "newScheme",
  addSubLocation = "addSubLocation",
  addSensors = "addSensors",
  newVerivRange = "newVersionRange",
  deleteControlSession = "deleteControlessSession",
  editProfile = "editProfile",
  confirmEmail = "confirmEmail",
}
